site_name: ns-lite
site_url: https://salar-prog.github.io/netscan-lite/
site_description: Lightweight IP discovery with quarantine logic
repo_url: https://github.com/Salar-prog/netscan-lite
repo_name: Salar-prog/netscan-lite

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - tables
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Install: install.md
  - Quick Start: quickstart.md
  - CLI Reference: cli.md
  - API Reference: api.md
  - Configuration: config.md
